language: php
git:
    depth: 5
php:
    - 7.4
install:
    - travis_retry composer clear-cache
    - travis_retry composer self-update
    - travis_retry composer install
script:
    - composer lint
    - composer test
